name: Auto Merge PRs at 23:58

on:
  schedule:
    - cron: '57 14 * * *' # 한국 시간 밤 11:58 = UTC 14:58
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        uses: cli/cli-action@v2

      - name: Auto Merge All Open PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list --state open --json number --jq '.[].number')
          
          for pr in $prs; do
            echo "Trying to auto-merge PR #$pr"
            gh pr merge $pr --auto --squash || echo "❌ Failed to merge PR #$pr"
          done
