name: Auto Merge PRs

on:
  schedule:
    - cron: '50 14 * * *' # 매일 밤 11:50 KST
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Merge All Open PRs into main (force if needed)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list --state open --json number,baseRefName --jq '.[] | select(.baseRefName=="main") | .number' --repo baesaa0304/CodingTest_Study)

          for pr in $prs; do
            echo "🔁 Trying to merge PR #$pr"
            gh pr merge "$pr" --repo baesaa0304/CodingTest_Study --squash --admin || echo "❌ Failed to merge PR #$pr"
          done
