name: Auto Merge PRs to Main

on:
  pull_request:
    branches:
      - main  # 모든 PR이 'main' 브랜치로 들어오는 경우만 자동 병합

  schedule:
    - cron: "15 14 * * *"  # 매일 오후 11시 15분(KST)에 실행

  workflow_dispatch:  # 수동 실행 가능

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}  # ✅ GH_TOKEN을 전체 job에서 사용 가능하도록 설정

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug PR List
        run: |
          echo "Listing PRs targeting 'main'..."
          gh pr list --state open --json number,baseRefName --jq '.[] | select(.baseRefName == "main") | .number'

      - name: Merge all PRs targeting 'main' (force commit)
        run: |
          for pr in $(gh pr list --state open --json number,baseRefName --jq '.[] | select(.baseRefName == "main") | .number'); do
            echo "Merging PR #$pr into main..."
            gh pr review --approve $pr  # 필요할 경우 자동 승인 추가
            gh pr merge --squash --admin $pr  # 즉시 병합 & 자동 커밋
          done
